language: php

php:
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache

install: composer install

script: make test

jobs:
  include:
    - name: Test against lowest allowed dependency versions
      php: '7.3'
      install: composer update --prefer-lowest
